version: '3'

services:
  database:
    image: "postgres:latest"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/posgresql/data
    ports:
      - 5432:5432


volumes:
  database-data: